### ISSUE TITLE
Ground-truth Point cloud registration with get_camera2world_matrix function is still incorrect

### ISSUE THREAD

**Issue by siddhantkatyan** [iaoqian/carla_3d-mapping_and_adding_virtual_objects#2]
Thanks for your contribution in fixing Carla data.transform.get_matrix() bug but I suspect that some issue still persists. 

I am trying to do ground-truth registration for two lidar frames collected with at a distance of two meters apart with a spectator view. I used your function to transform the lidar_matrix = self.get_camera2world_matrix(data.transform) 

Then I compute the relative transform based on the lidar_matrix of the two point cloud frames -     
```
def compute_relative_transform(self, source_pose, target_pose):
        """Compute the relative transformation matrix from source to target pose."""
        T_source = source_pose
        T_target = target_pose

        # Compute the inverse of the source transformation matrix
        T_source_inv = torch.inverse(T_source)

        # Compute the relative transformation
        T_relative = torch.mm(T_target, T_source_inv)
        return T_relative
```

And perform the registration using Open3D - gt_registered_pc = (source_pc).transform(gt_relative_transform)

But still there is a large error in translation but small error in rotation with the correct transform to register both the point clouds. 

_Note that this only happens when there is a change in the yaw and pitch of the two point cloud frames (e.g point cloud collected around a corner or a turn)_ Please let me know if you have any ideas to resolve this.

**Comment by kkaiwwana** [comment]
In this repo, I transform point cloud collected from Depth Camera of which coordinate system is NOT same as vehicle's (which follows standard UE setting, x -> forward, y -> turn right). Specifically, it follows an axes transformation: (x, y, z) -> (z', x'. -y') where  (x, y, z) and (z', x'. -y') is a point in camera system(screen space) and vehicle space respectively. That's why I need `camera2vehicle_matrix` which simply swaps axes, in function `get_camera2world_matrix()`:
```python
camera2vehicle_matrix = np.array([[0, 0, 1, 0], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1]], dtype=np.float64)
```
You can find more details about it in CARLA issue #553.

However, the point cloud collected by LiDAR is originally represented in word space, that line of code causes the error. If I was right, remove that matrix in your code or simply replace that with an eye(4) should solve your problem. (I'm not familiar with ground-truth registration and not active in CARLA for now, but your steps to process these data sound reasonable and your func `compute_relative_transform()` looks good to me).

Let me know if it works. Good luck.

**Comment by siddhantkatyan** [comment]
Thanks a lot for the quick reply.  Thanks for pointing out that the LiDAR is originally represented in the world coordinate space. I avoided the axes swap and changed the compute_relative_transform to compute the inverse of the target pose to do the ground-truth registration and it is working fine now. I wonder why such an important bug is not resolved in the latest CARLA release. Thanks again for your contribution.

**Comment by kkaiwwana** [comment]
I'm glad to hear that you found it helpful.

The reason they didn't fix it (most of them do not even notice that) is, I guess, this issues is innocent and too inconspicuous for those work mostly focus on single timesteps/frame, the "wrong transformation" can do the job, plausibly (e.g. it can draw 3d bbox to 2d camera screen "correctly", there is even an official demo). But it causes errors when multiple timesteps/frames data are incorporated. It has caused several issues, but they do not suspect the CARLA impl of this function (this is so fundamental that no one really supposes it could be wrong).

And unfortunately, the number of people maintaining CARLA had already dwindled by that time. With thousands of unresolved issues piling up, even fewer people would pay attention to this problem.
